server:
  port: 8888

spring:
  profiles:
    active: dev
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seremwen/SMS-Config-Files/
          default-label: main
          skip-ssl-validation: true
          clone-on-start: true